"""initial_schema

Revision ID: c26c9db320bf
Revises: 
Create Date: 2026-01-10 16:24:25.534893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c26c9db320bf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_providers',
    sa.Column('name', sa.Text(), nullable=False, comment="Provider name (e.g., 'openai', 'anthropic', 'google')"),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_providers_name'), 'llm_providers', ['name'], unique=True)
    op.create_table('prompt_tags',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('prompt_templates',
    sa.Column('name', sa.Text(), nullable=False, comment="Logical name grouping template versions (e.g., 'summarizer')"),
    sa.Column('version', sa.Integer(), nullable=False, comment='Sequential version number within this template name'),
    sa.Column('system_prompt', sa.Text(), nullable=True, comment='System prompt content'),
    sa.Column('user_prompt', sa.Text(), nullable=False, comment='User prompt template with {placeholders}'),
    sa.Column('description', sa.Text(), nullable=True, comment='What this template does'),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_template_name_version')
    )
    op.create_index(op.f('ix_prompt_templates_name'), 'prompt_templates', ['name'], unique=False)
    op.create_table('llm_models',
    sa.Column('provider_id', sa.UUID(as_uuid=False), nullable=False, comment='The provider this model belongs to'),
    sa.Column('api_model_name', sa.Text(), nullable=False, comment="Model identifier (e.g., 'gpt-4', 'claude-3-opus-20240229')"),
    sa.Column('display_name', sa.Text(), nullable=True, comment="Human-readable name (e.g., 'GPT-4', 'Claude 3 Opus')"),
    sa.Column('description', sa.Text(), nullable=True, comment="Description of the model's capabilities"),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this model is enabled for use'),
    sa.Column('is_deprecated', sa.Boolean(), nullable=False, comment='Whether this model is deprecated'),
    sa.Column('deprecation_date', sa.Text(), nullable=True, comment='Date when the model will be/was deprecated'),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['llm_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'api_model_name', name='uq_model_provider_name')
    )
    op.create_index(op.f('ix_llm_models_api_model_name'), 'llm_models', ['api_model_name'], unique=False)
    op.create_index(op.f('ix_llm_models_provider_id'), 'llm_models', ['provider_id'], unique=False)
    op.create_index('ix_model_active', 'llm_models', ['is_active'], unique=False)
    op.create_table('prompt_configs',
    sa.Column('template_id', sa.UUID(as_uuid=False), nullable=False, comment='The template this config uses'),
    sa.Column('name', sa.Text(), nullable=False, comment='Descriptive name for this config'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Config version (configs can also evolve)'),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON Schema defining expected input variables and types'),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON Schema or Pydantic schema for structured outputs'),
    sa.Column('output_format', sa.String(length=50), nullable=True, comment="Expected format: 'json', 'markdown', 'text', 'code', 'structured'"),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['prompt_templates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_config_name_version')
    )
    op.create_index(op.f('ix_prompt_configs_template_id'), 'prompt_configs', ['template_id'], unique=False)
    op.create_table('llm_configs',
    sa.Column('model_id', sa.UUID(as_uuid=False), nullable=False, comment='The model this config uses'),
    sa.Column('name', sa.Text(), nullable=False, comment="Unique name for this config (e.g., 'creative-writing', 'precise-extraction')"),
    sa.Column('description', sa.Text(), nullable=True, comment="Description of this configuration's purpose"),
    sa.Column('temperature', sa.Float(), nullable=True, comment='Temperature setting (0.0-2.0)'),
    sa.Column('extra_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional provider-specific settings: max_tokens, top_p, etc.'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this config is enabled'),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['llm_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_configs_model_id'), 'llm_configs', ['model_id'], unique=False)
    op.create_index(op.f('ix_llm_configs_name'), 'llm_configs', ['name'], unique=True)
    op.create_table('prompts',
    sa.Column('config_id', sa.UUID(as_uuid=False), nullable=False, comment='The config this prompt uses'),
    sa.Column('display_name', sa.Text(), nullable=True, comment='Human-readable name for UI'),
    sa.Column('description', sa.Text(), nullable=True, comment="Description of this prompt's purpose"),
    sa.Column('rendered_system_prompt', sa.Text(), nullable=True, comment='Final system prompt after variable substitution'),
    sa.Column('rendered_user_prompt', sa.Text(), nullable=True, comment='Final user prompt after variable substitution'),
    sa.Column('input_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Input values used to render the prompt'),
    sa.Column('environment', sa.Text(), nullable=False, comment="Target environment: 'development', 'staging', 'production'"),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this prompt is enabled'),
    sa.Column('category', sa.Text(), nullable=True, comment="Category: 'summarization', 'extraction', 'generation', etc."),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['prompt_configs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prompt_category_active', 'prompts', ['category', 'is_active'], unique=False)
    op.create_index('ix_prompt_environment', 'prompts', ['environment'], unique=False)
    op.create_index(op.f('ix_prompts_config_id'), 'prompts', ['config_id'], unique=False)
    op.create_table('prompt_responses',
    sa.Column('prompt_id', sa.UUID(as_uuid=False), nullable=False, comment='The prompt that generated this response'),
    sa.Column('llm_config_id', sa.UUID(as_uuid=False), nullable=True, comment='The LLM config used for this response'),
    sa.Column('llm_model_id', sa.UUID(as_uuid=False), nullable=True, comment='The LLM model that generated this response'),
    sa.Column('llm_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="LLM response: {'raw': 'text...', 'parsed': {...}}"),
    sa.Column('input_tokens', sa.Integer(), nullable=True, comment='Number of input tokens'),
    sa.Column('output_tokens', sa.Integer(), nullable=True, comment='Number of output tokens'),
    sa.Column('latency_ms', sa.Integer(), nullable=True, comment='Response latency in milliseconds'),
    sa.Column('success', sa.Boolean(), nullable=True, comment='Whether the response was successful'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if failed'),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['llm_config_id'], ['llm_configs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['llm_model_id'], ['llm_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_responses_llm_config_id'), 'prompt_responses', ['llm_config_id'], unique=False)
    op.create_index(op.f('ix_prompt_responses_llm_model_id'), 'prompt_responses', ['llm_model_id'], unique=False)
    op.create_index(op.f('ix_prompt_responses_prompt_id'), 'prompt_responses', ['prompt_id'], unique=False)
    op.create_index('ix_response_prompt_created', 'prompt_responses', ['prompt_id', 'created_at'], unique=False)
    op.create_table('prompt_tag_associations',
    sa.Column('prompt_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tag_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['prompt_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prompt_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prompt_tag_associations')
    op.drop_index('ix_response_prompt_created', table_name='prompt_responses')
    op.drop_index(op.f('ix_prompt_responses_prompt_id'), table_name='prompt_responses')
    op.drop_index(op.f('ix_prompt_responses_llm_model_id'), table_name='prompt_responses')
    op.drop_index(op.f('ix_prompt_responses_llm_config_id'), table_name='prompt_responses')
    op.drop_table('prompt_responses')
    op.drop_index(op.f('ix_prompts_config_id'), table_name='prompts')
    op.drop_index('ix_prompt_environment', table_name='prompts')
    op.drop_index('ix_prompt_category_active', table_name='prompts')
    op.drop_table('prompts')
    op.drop_index(op.f('ix_llm_configs_name'), table_name='llm_configs')
    op.drop_index(op.f('ix_llm_configs_model_id'), table_name='llm_configs')
    op.drop_table('llm_configs')
    op.drop_index(op.f('ix_prompt_configs_template_id'), table_name='prompt_configs')
    op.drop_table('prompt_configs')
    op.drop_index('ix_model_active', table_name='llm_models')
    op.drop_index(op.f('ix_llm_models_provider_id'), table_name='llm_models')
    op.drop_index(op.f('ix_llm_models_api_model_name'), table_name='llm_models')
    op.drop_table('llm_models')
    op.drop_index(op.f('ix_prompt_templates_name'), table_name='prompt_templates')
    op.drop_table('prompt_templates')
    op.drop_table('prompt_tags')
    op.drop_index(op.f('ix_llm_providers_name'), table_name='llm_providers')
    op.drop_table('llm_providers')
    # ### end Alembic commands ###
